version: "3.8"

services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_GITHUB_USERNAME=${NEXT_PUBLIC_GITHUB_USERNAME:-${VITE_GITHUB_USERNAME}}
        - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-${VITE_GITHUB_TOKEN}}
        - VITE_GITHUB_USERNAME=${VITE_GITHUB_USERNAME}
        - VITE_GITHUB_TOKEN=${VITE_GITHUB_TOKEN}
    container_name: web-profile
    restart: unless-stopped
    environment:
      - PORT=8383
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production

    ports:
      - "8383:8383"

    networks:
      - coolify

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      # HTTP Router (redireciona para HTTPS)
      - "traefik.http.routers.tayron-profile-http.rule=Host(`tayronrocha.com`)"
      - "traefik.http.routers.tayron-profile-http.entrypoints=web"
      - "traefik.http.routers.tayron-profile-http.middlewares=tayron-redirect-https"
      # HTTPS Router
      - "traefik.http.routers.tayron-profile.rule=Host(`tayronrocha.com`)"
      - "traefik.http.routers.tayron-profile.entrypoints=websecure"
      - "traefik.http.routers.tayron-profile.tls=true"
      - "traefik.http.routers.tayron-profile.tls.certresolver=letsencrypt"
      - "traefik.http.services.tayron-profile.loadbalancer.server.port=8383"
      # Middleware para redirecionamento HTTPS
      - "traefik.http.middlewares.tayron-redirect-https.redirectscheme.scheme=https"

networks:
  coolify:
    external: true
    name: coolify
